//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mobi是全球唯一专为手机及移动终端设备打造的域名，是为ICANN批准的全新国际顶级域名，其致力于将互联网信息传送到手机等移动设备上。此外mobi还是亚马逊电子书的专有格式，自从亚马逊推出kindle以来，这个阅读器的专用格式mobi就很流行。
        ///              rss4.mobi为用户将新鲜的电子报刊杂志推送到你的kindle或安装有kindle软件的移动设备上。你可以直接订阅本网站上提供的流行的新闻源，或者订阅你喜欢的任意博客和网站。 的本地化字符串。
        /// </summary>
        internal static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的账户 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活失败 的本地化字符串。
        /// </summary>
        internal static string ActivateFaild {
            get {
                return ResourceManager.GetString("ActivateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐号可能已经被激活过，或者激活链接已失效，请 的本地化字符串。
        /// </summary>
        internal static string ActivateFaildTip {
            get {
                return ResourceManager.GetString("ActivateFaildTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活成功 的本地化字符串。
        /// </summary>
        internal static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活成功,现在去 的本地化字符串。
        /// </summary>
        internal static string ActivateSuccessTip {
            get {
                return ResourceManager.GetString("ActivateSuccessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看详细 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费 的本地化字符串。
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精彩内容 的本地化字符串。
        /// </summary>
        internal static string HomeContent {
            get {
                return ResourceManager.GetString("HomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以在本站推荐的内容里订阅，也可以导入你的鲜果或谷歌GoogleReader订阅数据。 的本地化字符串。
        /// </summary>
        internal static string HomeContentDescription {
            get {
                return ResourceManager.GetString("HomeContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供由RSS订阅源转换为epub或mobi格式的免费在线服务,定时传送到你的kindle中,你可以把它当成一份每天更新并且免费的电子报纸/杂志!支持从鲜果或Google Reader中导入订阅信息. 的本地化字符串。
        /// </summary>
        internal static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费 的本地化字符串。
        /// </summary>
        internal static string HomeFree {
            get {
                return ResourceManager.GetString("HomeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供多达20个feed的免费RSS递送服务。每个feed条目数量不限，并且包括内容中图片。 的本地化字符串。
        /// </summary>
        internal static string HomeFreeDescription {
            get {
                return ResourceManager.GetString("HomeFreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时推送 的本地化字符串。
        /// </summary>
        internal static string HomeTime {
            get {
                return ResourceManager.GetString("HomeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以选择每天或者每周某个时间点，推送到你指定的kindle邮箱。支持亚马逊kindle以及多看iduokan等邮箱。 的本地化字符串。
        /// </summary>
        internal static string HomeTimeDescription {
            get {
                return ResourceManager.GetString("HomeTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的订阅 的本地化字符串。
        /// </summary>
        internal static string MyFeeds {
            get {
                return ResourceManager.GetString("MyFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新注册 的本地化字符串。
        /// </summary>
        internal static string ReRegister {
            get {
                return ResourceManager.GetString("ReRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名/邮箱 的本地化字符串。
        /// </summary>
        internal static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
    }
}
